#pragma once

#define ICON_APP							":/images/app.png"
#define IMG_BACK							":/images/back.png"

//Õÿ∆À—°‘Ò
#define ICON_SEL_SHAPE						":/Sel/Resources/Sel/SEL_Shape.png"
#define ICON_SEL_VERTEX						":/Sel/Resources/Sel/SEL_Vertex.png"
#define ICON_SEL_EDGE						":/Sel/Resources/Sel/SEL_Edge.png"
#define ICON_SEL_FACE						":/Sel/Resources/Sel/SEL_Face.png"
#define ICON_SEL_SOLID						":/Sel/Resources/Sel/SEL_Solid.png"

//OCC»˝Œ¨ ”Õº
#define ICON_VIEW_AXO						":/OccView/Resources/OccView/view_axo.png"
#define ICON_VIEW_BACK						":/OccView/Resources/OccView/view_back.png"
#define ICON_VIEW_BOTTOM					":/OccView/Resources/OccView/view_bottom.png"
#define ICON_VIEW_COMP_OFF					":/OccView/Resources/OccView/view_comp_off.png"
#define ICON_VIEW_COMP_ON					":/OccView/Resources/OccView/view_comp_on.png"
#define ICON_VIEW_FITALL					":/OccView/Resources/OccView/view_fitall.png"	
#define ICON_VIEW_FITAREA					":/OccView/Resources/OccView/view_fitarea.png"
#define ICON_VIEW_FRONT						":/OccView/Resources/OccView/view_front.png"
#define ICON_VIEW_GLPAN						":/OccView/Resources/OccView/view_glpan.png"
#define ICON_VIEW_LEFT						":/OccView/Resources/OccView/view_left.png"
#define ICON_VIEW_PAN						":/OccView/Resources/OccView/view_pan.png"
#define ICON_VIEW_RESET						":/OccView/Resources/OccView/view_reset.png"
#define ICON_VIEW_RIGHT						":/OccView/Resources/OccView/view_right.png"
#define ICON_VIEW_ROTATE					":/OccView/Resources/OccView/view_rotate.png"
#define ICON_VIEW_TOP						":/OccView/Resources/OccView/view_top.png"
#define ICON_VIEW_ZOOM						":/OccView/Resources/OccView/view_zoom.png"
#define ICON_VIEW_GLOBALPAN					":/OccView/Resources/OccView/view_globalpan.png"
#define ICON_CURSOR_ROTATE					":/OccView/Resources/OccView/cursor_rotate.png"
#define ICON_CURSOR_ZOOM					":/OccView/Resources/OccView/cursor_zoom.png"
#define ICON_RAYTRACE_ANTIALIASING			":/OccView/Resources/OccView/raytrace_antialiasing.png"
#define ICON_RAYTRACE_RAYTRACING			":/OccView/Resources/OccView/raytrace_raytracing.png"
#define ICON_RAYTRACE_REFLECTIONS			":/OccView/Resources/OccView/raytrace_reflections.png"
#define ICON_RAYTRACE_SHADOWS				":/OccView/Resources/OccView/raytrace_shadows.png"

//AIS
#define ICON_AIS_SELCOLOR					":/AIS/Resources/Ais/tool_selcolor.png"
#define ICON_AIS_OBJCOLOR					":/AIS/Resources/Ais/tool_objcolor.png"
#define ICON_AIS_DELETE						":/AIS/Resources/Ais/tool_delete.png"
#define ICON_AIS_MATERIAL					":/AIS/Resources/Ais/tool_material.png"
#define ICON_AIS_SHADING					":/AIS/Resources/Ais/tool_shading.png"
#define ICON_AIS_TRANSPARENCY				":/AIS/Resources/Ais/tool_transparency.png"
#define ICON_AIS_WIREFRAME					":/AIS/Resources/Ais/tool_wireframe.png"
#define ICON_AIS_ERASE						":/AIS/Resources/Ais/tool_erase.png"
#define ICON_AIS_ERASEALL					":/AIS/Resources/Ais/tool_eraseall.png"
#define ICON_AIS_DISPLAYALL					":/AIS/Resources/Ais/tool_displayall.png"
#define ICON_AIS_ATTACH						":/AIS/Resources/Ais/tool_Attach.png"
#define ICON_AIS_DETACH						":/AIS/Resources/Ais/tool_Detach.png"